# how to import data in python using pandas
written by: Dr. Allah Ditta Babar\
date: 07/08/2026\
Email: adbabar.nibge@gmail.com

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("pandas_01_day6.xlsx")

In [4]:
df

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

## View dataframes in pandas

In [6]:
df.head()

  Height Weight Favourite Dish
0    5.8    101  Chicken Pulao
1    6.2     92        Biryani
2    5.9     62  Karahi Ghosht
3    5.9     95  Chicken Pulao
4    5.9     55  Chicken Pulao

In [7]:
df.tail()

   Height Weight Favourite Dish
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

In [8]:
df.shape

(87, 3)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          87 non-null     object
 1   Weight          87 non-null     object
 2   Favourite Dish  87 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB

## Type casting

In [11]:
df.index

RangeIndex(start=0, stop=87, step=1)

In [14]:
df.columns

Index(['Height', 'Weight', 'Favourite Dish'], dtype='object')

In [16]:
df.describe()

        Height  Weight Favourite Dish
count     87.0      87             87
unique    35.0      47              5
top        5.9      55        Biryani
freq       9.0       6             40

In [17]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
Height,5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5’11,5'3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
Weight,101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,75KG,61,68,96
Favourite Dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani

In [18]:
df.sort_index()

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [19]:
df.sort_index(ascending=False)

   Height Weight Favourite Dish
86    5.1     96        Biryani
85    6.2     68  Chicken Pulao
84    5.4     61        Biryani
83    5.9   75KG  Karahi Ghosht
82    5.4     55          Pasta
..    ...    ...            ...
4     5.9     55  Chicken Pulao
3     5.9     95  Chicken Pulao
2     5.9     62  Karahi Ghosht
1     6.2     92        Biryani
0     5.8    101  Chicken Pulao

[87 rows x 3 columns]

In [20]:
df.sort_values(by="weight")

KeyError: 'weight'