In [1]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-06  0.178422  0.008277 -3.119820  0.782313

In [15]:
df2 = pd.DataFrame(
                  {
                  "A": 1.0,
                  "B": pd.Timestamp("20130102"),
                  "C": pd.Series(1, index=list(range(4)), dtype="float32"),
                  "D": np.array([3] * 4, dtype="int32"),
                  "E": pd.Categorical(["test", "train", "test", "train"]),
                  "F": "foo",
                  }
                  )

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [7]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [16]:
# Viewing data
df.head()

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814

In [17]:
df.tail()

                   A         B         C         D
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-06  0.178422  0.008277 -3.119820  0.782313

In [19]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')