In [1]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-06  0.178422  0.008277 -3.119820  0.782313

In [15]:
df2 = pd.DataFrame(
                  {
                  "A": 1.0,
                  "B": pd.Timestamp("20130102"),
                  "C": pd.Series(1, index=list(range(4)), dtype="float32"),
                  "D": np.array([3] * 4, dtype="int32"),
                  "E": pd.Categorical(["test", "train", "test", "train"]),
                  "F": "foo",
                  }
                  )

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [7]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [16]:
# Viewing data
df.head()

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814

In [17]:
df.tail()

                   A         B         C         D
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-06  0.178422  0.008277 -3.119820  0.782313

In [19]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [20]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [21]:
df.to_numpy()

array([[ 0.03702818,  2.87955028,  1.12396194, -0.05458917],
       [ 0.05621371, -0.03803631,  1.48317134, -0.96619017],
       [ 0.5303957 ,  0.2692953 ,  0.55732822,  0.376889  ],
       [-1.80654084,  1.95475436, -0.1528655 , -0.4054336 ],
       [ 0.85047726, -2.17841572,  0.84632523, -0.62881367],
       [ 0.17842157,  0.0082766 , -3.11981986,  0.78231336]])

In [22]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [23]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [24]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.025667  0.482571  0.123017 -0.149304
std    0.927430  1.762677  1.682606  0.650630
min   -1.806541 -2.178416 -3.119820 -0.966190
25%    0.041825 -0.026458  0.024683 -0.572969
50%    0.117318  0.138786  0.701827 -0.230011
75%    0.442402  1.533390  1.054553  0.269019
max    0.850477  2.879550  1.483171  0.782313

In [25]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.037028    0.056214    0.530396   -1.806541    0.850477    0.178422
B    2.879550   -0.038036    0.269295    1.954754   -2.178416    0.008277
C    1.123962    1.483171    0.557328   -0.152866    0.846325   -3.119820
D   -0.054589   -0.966190    0.376889   -0.405434   -0.628814    0.782313

In [ ]:
#sorts by an axis:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01 -0.054589  1.123962  2.879550  0.037028
2013-01-02 -0.966190  1.483171 -0.038036  0.056214
2013-01-03  0.376889  0.557328  0.269295  0.530396
2013-01-04 -0.405434 -0.152866  1.954754 -1.806541
2013-01-05 -0.628814  0.846325 -2.178416  0.850477
2013-01-06  0.782313 -3.119820  0.008277  0.178422

In [ ]:
#sorts by values:
df.sort_values(by="B")

                   A         B         C         D
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-06  0.178422  0.008277 -3.119820  0.782313
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-01  0.037028  2.879550  1.123962 -0.054589

## Selection

In [37]:
df

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434
2013-01-05  0.850477 -2.178416  0.846325 -0.628814
2013-01-06  0.178422  0.008277 -3.119820  0.782313

In [40]:
df.shape

(6, 4)

In [ ]:
df.iloc[0:2, 0:3] # index lock

                   A         B         C
2013-01-01  0.037028  2.879550  1.123962
2013-01-02  0.056214 -0.038036  1.483171

In [48]:
#Getitem ([])
df.loc[:,["A","B"]]

                   A         B
2013-01-01  0.037028  2.879550
2013-01-02  0.056214 -0.038036
2013-01-03  0.530396  0.269295
2013-01-04 -1.806541  1.954754
2013-01-05  0.850477 -2.178416
2013-01-06  0.178422  0.008277

In [29]:
df.A

2013-01-01    0.037028
2013-01-02    0.056214
2013-01-03    0.530396
2013-01-04   -1.806541
2013-01-05    0.850477
2013-01-06    0.178422
Freq: D, Name: A, dtype: float64

In [30]:
df[["B", "A"]]

                   B         A
2013-01-01  2.879550  0.037028
2013-01-02 -0.038036  0.056214
2013-01-03  0.269295  0.530396
2013-01-04  1.954754 -1.806541
2013-01-05 -2.178416  0.850477
2013-01-06  0.008277  0.178422

In [ ]:
#passing a slice, select three rows
df[0:3]

                   A         B         C         D
2013-01-01  0.037028  2.879550  1.123962 -0.054589
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889

In [33]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02  0.056214 -0.038036  1.483171 -0.966190
2013-01-03  0.530396  0.269295  0.557328  0.376889
2013-01-04 -1.806541  1.954754 -0.152866 -0.405434

## Selection by label

In [34]:
df.loc[dates[0]]

A    0.037028
B    2.879550
C    1.123962
D   -0.054589
Name: 2013-01-01 00:00:00, dtype: float64

In [36]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.037028  2.879550
2013-01-02  0.056214 -0.038036
2013-01-03  0.530396  0.269295
2013-01-04 -1.806541  1.954754
2013-01-05  0.850477 -2.178416
2013-01-06  0.178422  0.008277

In [50]:
df.iloc[3]

A   -1.806541
B    1.954754
C   -0.152866
D   -0.405434
Name: 2013-01-04 00:00:00, dtype: float64

In [51]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04 -1.806541  1.954754
2013-01-05  0.850477 -2.178416