In [14]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [51]:
# model
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# import the data in feature matrix
X = df[['age', 'fare']]
X.age.fillna(value = X['age'].mean(), inplace = True) # Replace missing scaled values with the median

# scaled data (-3 to +3)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## perform clustring
model = KMeans(n_clusters=5)
model.fit(X_scaled)

# assign cluster labels to data
df['cluster'] = model.labels_

C:\Users\Hp\AppData\Local\Temp\ipykernel_14028\2746978636.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X.age.fillna(value = X['age'].mean(), inplace = True) # Replace missing scaled values with the median
C:\Users\Hp\AppData\Local\Temp\ipykernel_14028\2746978636.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.age.fillna(value = X['age'].mean(), inplace = True) # Replace missing scaled values with the median

In [52]:
import joblib
joblib.dump(model, 'tips_model.joblib')

['tips_model.joblib']

In [37]:
import seaborn as sns
df_1 = sns.load_dataset('tips')
df_1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [38]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [39]:
df_1.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [40]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df_1['smoker'])
df_1['smoker'] = le.transform(df_1['smoker'])

In [41]:
le = LabelEncoder()
le.fit(df_1['day'])
df_1['day'] = le.transform(df_1['day'])

In [42]:
df_1

     total_bill   tip     sex  smoker  day    time  size
0         16.99  1.01  Female       0    2  Dinner     2
1         10.34  1.66    Male       0    2  Dinner     3
2         21.01  3.50    Male       0    2  Dinner     3
3         23.68  3.31    Male       0    2  Dinner     2
4         24.59  3.61  Female       0    2  Dinner     4
..          ...   ...     ...     ...  ...     ...   ...
239       29.03  5.92    Male       0    1  Dinner     3
240       27.18  2.00  Female       1    1  Dinner     2
241       22.67  2.00    Male       1    1  Dinner     2
242       17.82  1.75    Male       0    1  Dinner     2
243       18.78  3.00  Female       0    3  Dinner     2

[244 rows x 7 columns]

In [43]:
X.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [44]:
le = LabelEncoder()
le.fit(df_1['time'])
df_1['time'] = le.transform(df_1['time'])

In [45]:
df_1

     total_bill   tip     sex  smoker  day  time  size
0         16.99  1.01  Female       0    2     0     2
1         10.34  1.66    Male       0    2     0     3
2         21.01  3.50    Male       0    2     0     3
3         23.68  3.31    Male       0    2     0     2
4         24.59  3.61  Female       0    2     0     4
..          ...   ...     ...     ...  ...   ...   ...
239       29.03  5.92    Male       0    1     0     3
240       27.18  2.00  Female       1    1     0     2
241       22.67  2.00    Male       1    1     0     2
242       17.82  1.75    Male       0    1     0     2
243       18.78  3.00  Female       0    3     0     2

[244 rows x 7 columns]

In [46]:
df_1.head()

   total_bill   tip     sex  smoker  day  time  size
0       16.99  1.01  Female       0    2     0     2
1       10.34  1.66    Male       0    2     0     3
2       21.01  3.50    Male       0    2     0     3
3       23.68  3.31    Male       0    2     0     2
4       24.59  3.61  Female       0    2     0     4

In [47]:
X = df_1.drop(columns=['sex'])
y=df_1['sex']

In [48]:
X.head()

   total_bill   tip  smoker  day  time  size
0       16.99  1.01       0    2     0     2
1       10.34  1.66       0    2     0     3
2       21.01  3.50       0    2     0     3
3       23.68  3.31       0    2     0     2
4       24.59  3.61       0    2     0     4

In [49]:
y.head()

0    Female
1      Male
2      Male
3      Male
4    Female
Name: sex, dtype: category
Categories (2, object): ['Male', 'Female']

In [50]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X, y)

DecisionTreeClassifier()

In [ ]:
joblib.dump(model, 'DecisionTreeClassifier.joblib')

## Load Model

In [54]:
model_1 = joblib.load('tips_model.joblib')

In [ ]:
import pickle

# save the model in pickle format
with open('tips_model.pkl', 'wb') as f: # wb means write binary
    pickle.dump(model, f)

## Load pickle

In [ ]:
with open('tips_model.pkl', 'rb') as f: # rb means read binary
    loaded_model = pickle.load(f)